ALTER TABLE comunas ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE direcciones ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE modelos ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE tipos_vehiculo ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE vehiculos_cliente ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE detalle_reparaciones ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE repuestos ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;
ALTER TABLE marcas ADD COLUMN habilitado TINYINT DEFAULT 1 NOT NULL;