INSERT INTO paises (codigo_iso, nombre_pais, nacionalidad) VALUES
('AFG', 'Afganistán', 'afgano'),
('ALB', 'Albania', 'albanés'),
('DZA', 'Argelia', 'argelino'),
('AND', 'Andorra', 'andorrano'),
('AGO', 'Angola', 'angoleño'),
('ATG', 'Antigua y Barbuda', 'antiguano'),
('ARG', 'Argentina', 'argentino'),
('ARM', 'Armenia', 'armenio'),
('AUS', 'Australia', 'australiano'),
('AUT', 'Austria', 'austríaco'),
('AZE', 'Azerbaiyán', 'azerbaiyano'),
('BHS', 'Bahamas', 'bahameño'),
('BHR', 'Baréin', 'bareiní'),
('BGD', 'Bangladés', 'bangladesí'),
('BRB', 'Barbados', 'barbadense'),
('BLR', 'Bielorrusia', 'bielorruso'),
('BEL', 'Bélgica', 'belga'),
('BLZ', 'Belice', 'beliceño'),
('BEN', 'Benín', 'beninés'),
('BTN', 'Bután', 'butanés'),
('BOL', 'Bolivia', 'boliviano'),
('BIH', 'Bosnia y Herzegovina', 'bosnio'),
('BWA', 'Botsuana', 'botsuano'),
('BRA', 'Brasil', 'brasileño'),
('BRN', 'Brunéi', 'bruneano'),
('BGR', 'Bulgaria', 'búlgaro'),
('BFA', 'Burkina Faso', 'burkinés'),
('BDI', 'Burundi', 'burundés'),
('CPV', 'Cabo Verde', 'caboverdiano'),
('KHM', 'Camboya', 'camboyano'),
('CMR', 'Camerún', 'camerunés'),
('CAN', 'Canadá', 'canadiense'),
('CAF', 'República Centroafricana', 'centroafricano'),
('TCD', 'Chad', 'chadiano'),
('CHL', 'Chile', 'chileno'),
('CHN', 'China', 'chino'),
('COL', 'Colombia', 'colombiano'),
('COM', 'Comoras', 'comorense'),
('COG', 'Congo', 'congoleño'),
('COD', 'República Democrática del Congo', 'congoleño'),
('CRI', 'Costa Rica', 'costarricense'),
('HRV', 'Croacia', 'croata'),
('CUB', 'Cuba', 'cubano'),
('CYP', 'Chipre', 'chipriota'),
('CZE', 'Chequia', 'checo'),
('DNK', 'Dinamarca', 'danés'),
('DOM', 'República Dominicana', 'dominicano'),
('ECU', 'Ecuador', 'ecuatoriano'),
('EGY', 'Egipto', 'egipcio'),
('SLV', 'El Salvador', 'salvadoreño'),
('GNQ', 'Guinea Ecuatorial', 'ecuatoguineano'),
('ERI', 'Eritrea', 'eritreo'),
('EST', 'Estonia', 'estonio'),
('SWZ', 'Esuatini', 'suazi'),
('ETH', 'Etiopía', 'etíope'),
('FJI', 'Fiyi', 'fiyiano'),
('FIN', 'Finlandia', 'finlandés'),
('FRA', 'Francia', 'francés'),
('GAB', 'Gabón', 'gabonés'),
('GMB', 'Gambia', 'gambiano'),
('GEO', 'Georgia', 'georgiano'),
('DEU', 'Alemania', 'alemán'),
('GHA', 'Ghana', 'ghanés'),
('GRC', 'Grecia', 'griego'),
('GRD', 'Granada', 'granadino'),
('GTM', 'Guatemala', 'guatemalteco'),
('GIN', 'Guinea', 'guineano'),
('GNB', 'Guinea-Bisáu', 'guineano'),
('GUY', 'Guyana', 'guyanés'),
('HTI', 'Haití', 'haitiano'),
('HND', 'Honduras', 'hondureño'),
('HUN', 'Hungría', 'húngaro'),
('ISL', 'Islandia', 'islandés'),
('IND', 'India', 'indio'),
('IDN', 'Indonesia', 'indonesio'),
('IRN', 'Irán', 'iraní'),
('IRQ', 'Irak', 'iraquí'),
('IRL', 'Irlanda', 'irlandés'),
('ISR', 'Israel', 'israelí'),
('ITA', 'Italia', 'italiano'),
('JAM', 'Jamaica', 'jamaicano'),
('JPN', 'Japón', 'japonés'),
('JOR', 'Jordania', 'jordano'),
('KAZ', 'Kazajistán', 'kazajo'),
('KEN', 'Kenia', 'keniano'),
('KIR', 'Kiribati', 'kiribatiano'),
('KWT', 'Kuwait', 'kuwaití'),
('KGZ', 'Kirguistán', 'kirguís'),
('LAO', 'Laos', 'laosiano'),
('LVA', 'Letonia', 'letón'),
('LBN', 'Líbano', 'libanés'),
('LSO', 'Lesoto', 'lesotense'),
('LBR', 'Liberia', 'liberio'),
('LBY', 'Libia', 'libio'),
('LIE', 'Liechtenstein', 'liechtensteiniano'),
('LTU', 'Lituania', 'lituano'),
('LUX', 'Luxemburgo', 'luxemburgués'),
('MDG', 'Madagascar', 'malgache'),
('MWI', 'Malaui', 'malauí'),
('MYS', 'Malasia', 'malasio'),
('MDV', 'Maldivas', 'maldivo'),
('MLI', 'Malí', 'maliense'),
('MLT', 'Malta', 'maltés'),
('MHL', 'Islas Marshall', 'marshalés'),
('MRT', 'Mauritania', 'mauritano'),
('MUS', 'Mauricio', 'mauriciano'),
('MEX', 'México', 'mexicano'),
('FSM', 'Micronesia', 'micronesio'),
('MDA', 'Moldavia', 'moldavo'),
('MCO', 'Mónaco', 'monegasco'),
('MNG', 'Mongolia', 'mongol'),
('MNE', 'Montenegro', 'montenegrino'),
('MAR', 'Marruecos', 'marroquí'),
('MOZ', 'Mozambique', 'mozambiqueño'),
('MMR', 'Birmania', 'birmano'),
('NAM', 'Namibia', 'namibio'),
('NRU', 'Nauru', 'nauruano'),
('NPL', 'Nepal', 'nepalí'),
('NLD', 'Países Bajos', 'neerlandés'),
('NZL', 'Nueva Zelanda', 'neozelandés'),
('NIC', 'Nicaragua', 'nicaragüense'),
('NER', 'Níger', 'nigerino'),
('NGA', 'Nigeria', 'nigeriano'),
('MKD', 'Macedonia del Norte', 'macedonio'),
('NOR', 'Noruega', 'noruego'),
('OMN', 'Omán', 'omaní'),
('PAK', 'Pakistán', 'pakistaní'),
('PLW', 'Palaos', 'palauano'),
('PAN', 'Panamá', 'panameño'),
('PNG', 'Papúa Nueva Guinea', 'papú'),
('PRY', 'Paraguay', 'paraguayo'),
('PER', 'Perú', 'peruano'),
('PHL', 'Filipinas', 'filipino'),
('POL', 'Polonia', 'polaco'),
('PRT', 'Portugal', 'portugués'),
('QAT', 'Catar', 'catarí'),
('ROU', 'Rumania', 'rumano'),
('RUS', 'Rusia', 'ruso'),
('RWA', 'Ruanda', 'ruandés'),
('KNA', 'San Cristóbal y Nieves', 'sancristobaleño'),
('LCA', 'Santa Lucía', 'santalucense'),
('VCT', 'San Vicente y las Granadinas', 'sanvicentino'),
('WSM', 'Samoa', 'samoano'),
('SMR', 'San Marino', 'sanmarinense'),
('STP', 'Santo Tomé y Príncipe', 'santomense'),
('SAU', 'Arabia Saudita', 'saudí'),
('SEN', 'Senegal', 'senegalés'),
('SRB', 'Serbia', 'serbio'),
('SYC', 'Seychelles', 'seychelense'),
('SLE', 'Sierra Leona', 'sierraleonés'),
('SGP', 'Singapur', 'singapurense'),
('SVK', 'Eslovaquia', 'eslovaco'),
('SVN', 'Eslovenia', 'esloveno'),
('SLB', 'Islas Salomón', 'salomonense'),
('SOM', 'Somalia', 'somalí'),
('ZAF', 'Sudáfrica', 'sudafricano'),
('KOR', 'Corea del Sur', 'surcoreano'),
('SSD', 'Sudán del Sur', 'sursudanés'),
('ESP', 'España', 'español'),
('LKA', 'Sri Lanka', 'ceilanés'),
('SDN', 'Sudán', 'sudanés'),
('SUR', 'Surinam', 'surinamés'),
('SWE', 'Suecia', 'sueco'),
('CHE', 'Suiza', 'suizo'),
('SYR', 'Siria', 'sirio'),
('TWN', 'Taiwán', 'taiwanés'),
('TJK', 'Tayikistán', 'tayiko'),
('TZA', 'Tanzania', 'tanzano'),
('THA', 'Tailandia', 'tailandés'),
('TLS', 'Timor Oriental', 'timorense'),
('TGO', 'Togo', 'togolés'),
('TON', 'Tonga', 'tongano'),
('TTO', 'Trinidad y Tobago', 'trinitense'),
('TUN', 'Túnez', 'tunecino'),
('TUR', 'Turquía', 'turco'),
('TKM', 'Turkmenistán', 'turcomano'),
('UGA', 'Uganda', 'ugandés'),
('UKR', 'Ucrania', 'ucraniano'),
('ARE', 'Emiratos Árabes Unidos', 'emiratí'),
('GBR', 'Reino Unido', 'británico'),
('USA', 'Estados Unidos', 'estadounidense'),
('URY', 'Uruguay', 'uruguayo'),
('UZB', 'Uzbekistán', 'uzbeko'),
('VEN', 'Venezuela', 'venezolano'),
('VNM', 'Vietnam', 'vietnamita'),
('YEM', 'Yemen', 'yemení'),
('ZMB', 'Zambia', 'zambiano'),
('ZWE', 'Zimbabue', 'zimbabuense');